<a href="https://colab.research.google.com/github/sumunoh/study_assemble/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치(PyTorch)

<img src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbuUgoV%2FbtqwWZvcHHX%2Fd6XzIFBEfiuFb0UvyV4A50%2Fimg.jpg" width="300">

- 코드 출처: https://pytorch.org/tutorials/

## 파이토치의 구성요소

- `torch`: 텐서를 생성하는 라이브러리

- `torch.autograd`: 자동미분 기능을 제공하는 라이브러리

- `torch.nn`: 신경망을 생성하는 라이브러리

- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리

- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공

- `torch.legacy`(./nn/.optim): Torch로부터 포팅해온 코드

- `torch.onnx`: ONNX(Open Neural Network Exchange)

  - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 넘파이(NumPy)의 ndarray와 유사

- GPU를 사용한 연산 가속도 가능

In [1]:
import torch

In [2]:
torch.__version__

'1.10.0+cu111'

### 초기화 되지 않은 행렬 

In [3]:
x = torch.empty(4,2)
print(x)

tensor([[5.4623e-05, 3.0932e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30]])


### 무작위로 초기화된 행렬

In [4]:
x = torch.rand(4,2)
print(x)

tensor([[0.2519, 0.7386],
        [0.1790, 0.3017],
        [0.3395, 0.0277],
        [0.9694, 0.3511]])


### dtype이 long, 0으로 채워진 텐서

In [5]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [6]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [7]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4004, -0.9814, -0.3485, -1.1647],
        [ 1.3984,  1.0486, -1.3234, -0.4801]])


### 텐서의 크기

In [9]:
print(x.size())

torch.Size([2, 4])


## 텐서의 연산(operations)

### 덧셈 1

In [10]:
print(x)

tensor([[-0.4004, -0.9814, -0.3485, -1.1647],
        [ 1.3984,  1.0486, -1.3234, -0.4801]])


In [11]:
y = torch.rand(2,4)
print(y)
print(x+y)

tensor([[0.2997, 0.8385, 0.7855, 0.3492],
        [0.6183, 0.9612, 0.1214, 0.7539]])
tensor([[-0.1007, -0.1428,  0.4371, -0.8155],
        [ 2.0167,  2.0099, -1.2020,  0.2737]])


### 덧셈2

In [12]:
print(torch.add(x,y))

tensor([[-0.1007, -0.1428,  0.4371, -0.8155],
        [ 2.0167,  2.0099, -1.2020,  0.2737]])


### 덧셈3
- 결과 텐서를 인자로 제공

In [13]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[-0.1007, -0.1428,  0.4371, -0.8155],
        [ 2.0167,  2.0099, -1.2020,  0.2737]])


### 덧셈4
- `in-place` 방식

- (참고) in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [14]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[-0.4004, -0.9814, -0.3485, -1.1647],
        [ 1.3984,  1.0486, -1.3234, -0.4801]])
tensor([[0.2997, 0.8385, 0.7855, 0.3492],
        [0.6183, 0.9612, 0.1214, 0.7539]])
tensor([[-0.1007, -0.1428,  0.4371, -0.8155],
        [ 2.0167,  2.0099, -1.2020,  0.2737]])


### 그 외의 연산
- `torch.sub` : 뺄셈

- `torch.mul` : 곱셉

- `torch.div` : 나눗셈

- `torch.mm` : 내적(dot product)

In [15]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [16]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [17]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [19]:
# 행렬곱
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(torch.mm(x,y))

tensor([[20., 28.],
        [52., 76.]])


## 텐서의 조작(manipulations)

### 인덱싱
- 넘파이처럼 인덱싱 사용가능

In [20]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [21]:
print(x[:, 1])

tensor([3., 7.])


### view
- 텐서의 크기(size)나 모양(shape)을 변경

In [22]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(5, -1)

print(x)
print(y)
print(z)

tensor([[ 0.4639, -2.3990,  0.6991,  0.4616, -0.8157],
        [-0.0836, -0.9492, -0.0160, -0.5664, -1.0807],
        [-0.3419, -1.0234,  0.3289,  1.0998,  0.8417],
        [ 1.7682, -0.0242,  0.1195,  0.6466,  1.1310]])
tensor([ 0.4639, -2.3990,  0.6991,  0.4616, -0.8157, -0.0836, -0.9492, -0.0160,
        -0.5664, -1.0807, -0.3419, -1.0234,  0.3289,  1.0998,  0.8417,  1.7682,
        -0.0242,  0.1195,  0.6466,  1.1310])
tensor([[ 0.4639, -2.3990,  0.6991,  0.4616],
        [-0.8157, -0.0836, -0.9492, -0.0160],
        [-0.5664, -1.0807, -0.3419, -1.0234],
        [ 0.3289,  1.0998,  0.8417,  1.7682],
        [-0.0242,  0.1195,  0.6466,  1.1310]])


### item
- 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음


In [23]:
x = torch.randn(1)
print(x)
print(x.item()) # 실제값 출력
print(x.dtype)

tensor([0.3323])
0.33228033781051636
torch.float32


- 스칼라값 하나만 존재해야함

In [24]:
x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.1161, -0.1482])


ValueError: ignored

### squeeze 
- 차원을 축소(제거)

In [27]:
tensor = torch.rand(1,3,3)
print(tensor)
tensor.shape

tensor([[[0.2876, 0.5879, 0.0566],
         [0.1585, 0.1388, 0.6901],
         [0.9074, 0.5102, 0.0075]]])


torch.Size([1, 3, 3])

In [28]:
t = tensor.squeeze()

print(t)
print(t.shape)

tensor([[0.2876, 0.5879, 0.0566],
        [0.1585, 0.1388, 0.6901],
        [0.9074, 0.5102, 0.0075]])
torch.Size([3, 3])


### unsqueeze
- 차원을 증가(생성)

In [29]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.7629, 0.1147, 0.1132],
         [0.7027, 0.2210, 0.8526],
         [0.2541, 0.4757, 0.8917]]])
torch.Size([1, 3, 3])


In [30]:
t = tensor.unsqueeze(dim=0)

print(t)
print(t.shape)

tensor([[[[0.7629, 0.1147, 0.1132],
          [0.7027, 0.2210, 0.8526],
          [0.2541, 0.4757, 0.8917]]]])
torch.Size([1, 1, 3, 3])


### stack
- 텐서간 결합

In [31]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### cat
- 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 dim이 존재해야함
  - 예를 들어, 해당 차원을 늘려준 후 결합


In [34]:
a = torch.randn(1,3,3)
b = torch.randn(1,3,3)
c = torch.cat((a,b), dim=1)

print(c)
print(c.size())

tensor([[[-0.0378,  0.3127,  0.8107],
         [-0.4458, -1.1158, -1.4534],
         [ 1.2015, -1.1225, -1.4003],
         [-0.0212,  1.5646, -0.5531],
         [-1.2865,  0.9630, -0.8783],
         [ 0.4378, -0.3369, -1.4034]]])
torch.Size([1, 6, 3])


### chuck
- 텐서를 여러 개로 나눌 때 사용

- 몇 개의 텐서로 나눌 것이냐

In [35]:
tensor = torch.rand(3, 6)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.8795, 0.2430, 0.4649, 0.4619, 0.7860, 0.6349],
        [0.6371, 0.5261, 0.7108, 0.1003, 0.4192, 0.6017],
        [0.3332, 0.5087, 0.2694, 0.4892, 0.9145, 0.0532]])
tensor([[0.8795, 0.2430],
        [0.6371, 0.5261],
        [0.3332, 0.5087]])
tensor([[0.4649, 0.4619],
        [0.7108, 0.1003],
        [0.2694, 0.4892]])
tensor([[0.7860, 0.6349],
        [0.4192, 0.6017],
        [0.9145, 0.0532]])


### split
- `chunck`와 동일한 기능이지만 조금 다름

- 하나의 텐서당 크기가 얼마이냐

In [37]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)

tensor([[0.9999, 0.3581, 0.7677, 0.7497, 0.4772, 0.7898],
        [0.9771, 0.9998, 0.5682, 0.5820, 0.8552, 0.2342],
        [0.4835, 0.8219, 0.4104, 0.9740, 0.6383, 0.0251]])
tensor([[0.9999, 0.3581, 0.7677],
        [0.9771, 0.9998, 0.5682],
        [0.4835, 0.8219, 0.4104]])
tensor([[0.7497, 0.4772, 0.7898],
        [0.5820, 0.8552, 0.2342],
        [0.9740, 0.6383, 0.0251]])


### torch ↔ numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능

  - `numpy()`
  - `from_numpy()`

- (참고)
  - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [38]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [40]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [43]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
- `.to` 메소드를 사용하여 텐서를 어떠한 장치로도 옮길 수 있음
  - 예) cpu, gpu

In [44]:
import torch

In [46]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.4738])
-0.4737919270992279
torch.float32


In [48]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(device)
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([0.5262], device='cuda:0')
tensor([0.5262], dtype=torch.float64)


## AUTOGRAD (자동미분)
- autograd 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공

- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻

- backprop를 위한 미분값을 자동으로 계산


-----------------------------------------------36:00

### Tensor

- data: tensor형태의 데이터

- grad: data가 겨쳐온 layer에 대한 미분값 저장

- grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

- `requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

- 계산이 완료된 후, `.backward()`를 호출하면 자동으로 `gradient`를 계산할 수 있으며, `.grad` 속성에 누적됨

- 기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad():`로 감싸면 `gradient`는 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

- Autograd 구현에서 매우 중요한 클래스 : `Function` 클래스

- `requires_grad_(...)`는 기존 텐서의 `requires_grad`값을 바꿔치기(`in-place`)하여 변경

### 기울기(Gradient)
- 역전파: `.backward()`를 통해 역전파 계산 가능

- `with torch.no_grad()`를 사용하여 gradient의 업데이트를 하지 않음

- `detach()`: 내용물(content)은 같지만 require_grad가 다른 새로운 Tensor를 가져올 때

### 자동 미분 흐름 다시 보기(1)
- 계산 흐름  
  $a \rightarrow b  \rightarrow c  \rightarrow out $

<br>

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해  
  $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면  
    $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐


- $b = a + 2$

- $c = b^2$ 

- a의 `grad_fn`이 None인 이유  
  직접적으로 계산한 부분이 없었기 때문

### 자동 미분 흐름 다시 보기(2)
- `grad`값을 넣어서 `backward`

- 아래의 코드에서 `.grad`값이 None은 gradient값이 필요하지 않기 때문

## nn & nn.functional

- 두 패키지가 같은 기능이지만 방식이 조금 다름

- 위의 `autograd` 관련 작업들을 두 패키지를 통해 진행할 수 있음

- 텐서를 직접 다룰 때 `requires_grad`와 같은 방식으로 진행할 수 있음

- 결론적으로, `torch.nn`은 attribute를 활용해 state를 저장하고 활용하고,  
  `torch.nn.functional`로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능
 


### nn 패키지

- 주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때  
  - 따라서, `weight`값들을 직접 선언 안함

- 예시
  - Containers

  - Convolution Layers

  - Pooling layers

  - Padding Layers

  - Non-linear Activations (weighted sum, nonlinearity)

  - Non-linear Activations (other)

  - Normalization Layers

  - Recurrent Layers

  - Transformer Layers

  - Linear Layers

  - Dropout Layers

  - Sparse Layers

  - Distance Functions

  - Loss Functions

  - ..
- https://pytorch.org/docs/stable/nn.html



- Convolution Layer 예시 (1)


### nn.functional 패키지

- 가중치를 직접 선언하여 인자로 넣어줘야함

- 예시)
  - Convolution functions

  - Pooling functions
  
  - Non-linear activation functions

  - Normalization functions

  - Linear functions

  - Dropout functions
  
  - Sparse functions
  
  - Distance functions

  - Loss functions
  - ..

- https://pytorch.org/docs/stable/nn.functional.html

- Convolution Layer 예시 (2)

## Torchvision

- `transforms`: 전처리할 때 사용하는 메소드

- `transforms`에서 제공하는 클래스 이외에  
  일반적으로 클래스를 따로 만들어 전처리 단계를 진행
  
  - 아래의 코드에서 다양한 전처리 기술 확인  
    https://pytorch.org/docs/stable/torchvision/transforms.html


- 예시)
  - `DataLoader`의 인자로 들어갈 `transform`을 미리 정의할 수 있음

  - `Compose`를 통해 리스트 안에 순서대로 전처리 진행

  - 대표적인 예로, `ToTensor`()를 하는 이유는  
   <u>torchvision이 PIL Image형태로만 입력을 받기 때문에</u> 데이터 처리를 위해서 Tensor형으로 변환해야함

## utils.data

- `Dataset`에는 다양한 데이터셋이 존재  
  - MNIST, CIFAR10, ...

- `DataLoader`, `Dataset`을 통해  
  `batch_size`, `train`여부, `transform`등을 인자로 넣어 데이터를 어떻게 load할 것인지 정해줄 수 있음

- `batch_size`만큼 데이터를 하나씩 가져옴

<u>**(중요) torch에서는 channel(채널)이 앞에 옴**</u>

- `channel first`

- tensorflow, keras 등에서는 channel이 뒤에 옴(`channel last`)

### 데이터 확인

## 각 Layer 설명

### nn.Conv2d

- `in_channels`: channel의 갯수

- `out_channels`: 출력 채널의 갯수

- `kernel_size`: 커널(필터) 사이즈

- 텐서플로우, 케라스와 다르게 레이어의 `input`인자에도 값을 집어 넣어줘야함

- `wegiht`확인

- `weight`는 `detach()`를 통해 꺼내줘야 `numpy()`변환이 가능

### Pooling
- `F.max_pool2d` 
  - `stride`

  - `kernel_size`

- `torch.nn.MaxPool2d` 도 많이 사용

- MaxPool Layer는 weight가 없기 때문에 바로 `numpy()`변환 가능

### Linear
- 1d만 가능 `.view()`를 통해 1D로 펼쳐줘야함

### Softmax

### F.relu

- ReLU 함수를 적용하는 레이어

- `nn.ReLU`로도 사용 가능

## Optimizer

- `import torch.optim as optim`

- `model`의 파라미터를 업데이트

- 예시)
  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
  optimizer = optim.SGD(model.parameters(), lr=0.001)
  ```

- `.zero_grad()`로 초기화
- `.step()`으로 업데이트

